---
- name: apt update
  apt:
    update_cache: yes
- name: Install haproxy
  apt:
    name: haproxy
    state: present
- name: configure haproxy
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
- name: restart haproxy
  service:
    name: haproxy
    state: restarted
