---
- hosts: all
  become: yes
  tasks:
   - name: apt
     apt:
      update_cache: yes
      upgrade: 'yes'

   - name: apt
     apt:
      name: software-properties-common
   - name: Add deadsnakes ppa
     ansible.builtin.apt_repository:
       repo: ppa:deadsnakes/ppa   
       update_cache: yes
   - name: install python version 3.8
     apt: 
      name: python
      state: latest
      update_cache: yes
